name: Commit Workflow
on:
  push
jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    name: Run Cypress Tests
    container:
      image: cypress/browsers:node18.12.0-chrome107
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./react-frontend
          build: npm run build
          start: npm start

